# This file provides an example configuration file
# Workers may have multiple origins, and will probe with each unique origin
# Workers will listen for every anycast origin defined (regardless of whether they are probing with the defined origin)
# A hostname can be used instead of a worker_id (e.g., nl-ams: (...))
# 'ALL' means all clients will probe using the defined origin
# 'unicast' as src_addr means each worker probes from its own local unicast address
# IPv4 and IPv6 origins may be mixed; each hitlist target can only be probed by origins matching its IP version
# Worker, src_addr, src_port, dst_port, protocol
# Wildcards are allowed in the worker field, e.g., us-* to select all workers with a hostname starting with 'us-'
ALL, 1.1.1.1, 1234, 4321, tcp
ALL, unicastv4, 1234, 4321, ICMP
ALL, 2001:db8::1, 1234, 4321, ICMP
ALL, unicastv6, 1234, 4321, ICMP
17, 1.1.1.2, 1234, 4321, ICMP
nl-ams, 1.1.1.3, 189, 53, DNS
us-*, 1.1.1.3, 189, 53, chaos
